name: iOS Build

   on:
     push:
       branches:
         - main

   jobs:
     build:
       runs-on: macos-latest

       steps:
         - name: Checkout the code
           uses: actions/checkout@v2

         - name: Set up Ruby
           uses: ruby/setup-ruby@v1
           with:
             ruby-version: 2.7

         - name: Install Cocoapods
           run: |
             sudo gem install cocoapods
             pod install
           working-directory: ./YOUR_PROJECT_DIRECTORY

         - name: Set up Xcode
           uses: maxim-lobanov/setup-xcode@v1
           with:
             xcode-version: '12.5'

         - name: Build the app
           run: |
             xcodebuild -workspace YOUR_PROJECT.xcworkspace -scheme YOUR_SCHEME -sdk iphoneos -configuration AppStoreDistribution build CODE_SIGN_IDENTITY="Apple Distribution: your-apple-id (TEAM_ID)" PROVISIONING_PROFILE="your-provisioning-profile-uuid"

         - name: Generate IPA
           run: |
             xcodebuild -workspace YOUR_PROJECT.xcworkspace -scheme YOUR_SCHEME -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/YOUR_PROJECT.xcarchive CODE_SIGN_IDENTITY="Apple Distribution: your-apple-id (TEAM_ID)" PROVISIONING_PROFILE="your-provisioning-profile-uuid"
             xcodebuild -exportArchive -archivePath $PWD/build/YOUR_PROJECT.xcarchive -exportPath $PWD/build -exportOptionsPlist YOUR_EXPORT_OPTIONS_PLIST_PATH
           env:
             # You may need to add additional environment variables for codesigning
             APPLE_ID: ${{ secrets.APPLE_ID }}
             APPLE_DEVELOPER_PASSWORD: ${{ secrets.APPLE_DEVELOPER_PASSWORD }}
             APPLE_DEVELOPER_TEAM_ID: ${{ secrets.APPLE_DEVELOPER_TEAM_ID }}
   
